services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: jutjubic
      POSTGRES_USER: jutjubic
      POSTGRES_PASSWORD: jutjubic
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api1:
    build: .
    environment:
      INSTANCE_ID: "api-1"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jutjubic
      SPRING_DATASOURCE_USERNAME: jutjubic
      SPRING_DATASOURCE_PASSWORD: jutjubic
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: never
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "false"

      # ✅ Rabbit NA HOSTU
      SPRING_RABBITMQ_HOST: host.docker.internal
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_RABBITMQ_LISTENER_SIMPLE_AUTO_STARTUP: "true"
    depends_on:
      - db
    expose:
      - "8080"

  api2:
    build: .
    environment:
      INSTANCE_ID: "api-2"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jutjubic
      SPRING_DATASOURCE_USERNAME: jutjubic
      SPRING_DATASOURCE_PASSWORD: jutjubic
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: never
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "false"

      # ✅ Rabbit NA HOSTU
      SPRING_RABBITMQ_HOST: host.docker.internal
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_RABBITMQ_LISTENER_SIMPLE_AUTO_STARTUP: "true"
    depends_on:
      - db
    expose:
      - "8080"

  lb:
    image: haproxy:2.9
    ports:
      - "8088:8080"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
